name: ble_parser
description: A Dart/Flutter code generation library for parsing Bluetooth Low Energy (BLE) byte data into typed objects.
version: 1.0.0
homepage: https://github.com/playwind/flutter_ble_parser
repository: https://github.com/playwind/flutter_ble_parser
issue_tracker: https://github.com/playwind/flutter_ble_parser/issues
license: MIT

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.3.0
  lints: ^6.0.0
  test: ^1.25.6

